### PR TITLE
Adding `metadata` to the README as a build argument

### PR DESCRIPTION
**Pull request by charliegroll**
## Goal

`metadata` can contain important, free-form build information

## Design

Types don't exist in this repo (I plan on adding them to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b9a1f5dcc0ce872829ee85e5c43c7f3e96970333/types/webpack-bugsnag-plugins/index.d.ts#L116

## Changeset

The README now contains `metadata` as an accepted build argument

## Testing

It works for our builds, so just add any k/v pair(s) to any build as `metadata`

### CODE REVIEW

**Comment by johnkiely1** [comment]
Hi @charliegroll. 
Thanks for this. 
We will review shortly.

**Review by johnkiely1 — APPROVED** [review]

**Comment by johnkiely1** [comment]
@charliegroll, we are looking into the failures now and will merge the PR in once we have them resolved.

**Comment by johnkiely1** [comment]
Hey @charliegroll, if you pull the latest from `next` into your branch it should fix the build issues.

**Comment by charliegroll** [comment]
@johnkiely1 done - if you want a rebase lemme know

**Pull request merged**
