### PR TITLE
codeBundleId support

### PR DESCRIPTION
**Pull request by farfromrefug**
I have tested it and it works perfectly!

### CODE REVIEW

**Comment by mattdyoung** [comment]
Hi @farfromrefug 

What's your intended usage for this? The `codeBundleId` is intended to support CodePush release on React Native apps whereas our Webpack plugin is intended for use on Javascript projects.

We're interested in the problem you're trying to solve here in case there may be a better solution with our existing tools or some of our in-flight development.

**Comment by farfromrefug** [comment]
I explained it in an issue here. I need it for  Nativescript. In {N} we use a mix of webpack/gradle for Android and webpack/pod for ios. This is the only part missing for me to make sure I have the right source maps for my beta builds (depending on the code bundle Id)

**Comment by mattdyoung** [comment]
Thanks, I hadn't spotted the issue.

Fixes https://github.com/bugsnag/webpack-bugsnag-plugins/issues/38

**Comment by farfromrefug** [comment]
@mattdyoung any news on this?

**Pull request merged**
